Yonal development
edumorlom/moms-infants-healthy pull request #146
Opened 2020-10-07 17:15 UTC by yhern185

Issue #121 pull request.
Please let me know if everything checks out fine.

2020-10-07 18:44 UTC, edumorlom requested changes

2020-10-07 18:44 UTC, edumorlom commented on src/en_US.json
> +<<<<<<< HEAD
This won't compile, you have to fix this.

2020-10-07 19:11 UTC, edumorlom commented
I see you added the .vs directory to the PR, please remove that too

2020-10-12 02:23 UTC, yhern185 commented
Hi Eduardo, 

I can see the change as been introduced already.

Did you merge it?

2020-10-12 04:55 UTC, edumorlom commented
What do you mean? It hasn't been merged yet. It's not in develop yet.

2020-10-14 03:09 UTC, closed without merging