#124 FemaleCondom clean up.
edumorlom/moms-infants-healthy pull request #152
Opened 2020-10-08 18:15 UTC by LeonelADiaz

#124 Clean up and merged into one file.

2020-10-08 20:03 UTC, edumorlom requested changes

2020-10-08 20:03 UTC, edumorlom commented on src/Components/FemaleCondom.jsx
> +<<<<<<< HEAD
I think u forgot to fix this merging conflict :)

2020-10-08 21:52 UTC, LeonelADiaz commented on src/Components/FemaleCondom.jsx
> +<<<<<<< HEAD
Sorry about that, should be good now!

2020-10-08 23:03 UTC, edumorlom approved these changes
Looks good, was tested correct?

2020-10-09 00:18 UTC, LeonelADiaz commented
> 
> 
> Looks good, was tested correct?

Yup. Works exactly as before, just now in one file. 

There was old code there commented out that attempted to solve an onBack() issue. When you press back on either the Condom Steps or Do/Dont screens, they take you back to the Learn screen instead of the Female Condom screen. I'll open this up as a new issue.

2020-10-09 16:37 UTC, merged