Resolving issue #131
edumorlom/moms-infants-healthy pull request #163
Opened 2020-10-09 16:49 UTC by Davidantu

Added phone number and DOB validation in the settings screen. Prints an alert whenever a phone number is invalid and/or a DOB is invalid. Preventing the user from saving wrong information to their profiles.

2020-10-10 18:53 UTC, edumorlom requested changes

2020-10-10 18:53 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +    if (validatePhone(PhoneNumber) == false) {
```suggestion
    if (validatePhone(PhoneNumber) === false) {
```

2020-10-10 18:53 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +    } else if (validateDOB(Dob) == false) {
```suggestion
    } else if (validateDOB(Dob) === false) {
```

2020-10-10 18:53 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +    var phoneno = /^\d{10}$/;
Don't use var. Use let instead. In this case you can even use const.

Rename phoneno to phoneNoRegex

2020-10-10 18:53 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +    var dateob =/^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/;
Same here. Const and dobRegex.

2020-10-10 18:53 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +    if ((Dob.match(dateob))) {
You don't need an if statement.

`return Dob.match(dateob)` will return true or false

2020-10-12 20:21 UTC, Davidantu commented
Updated it to be able to also check for validity in Infant DOB also made some changes to the way alerts pop up, to make it only show one alert, instead of in worst case for example 3.

2020-10-12 21:32 UTC, edumorlom requested changes

2020-10-12 21:32 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +      validateBaby(BabyDOB) === false
Isn't validateBaby(BabyDOB) always gonna be true?
You aren't passing Infant, if you don't pass Infant the function will return true as per the if statement.

![image](https://user-images.githubusercontent.com/11444894/95792077-b8d9f000-0cb0-11eb-9e6d-89d90c86d028.png)

2020-10-12 21:32 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +      validateDOB(Dob) === false ||
Dob = dob
PhoneNumber = phoneNumber
BabyDOB = babyDob

2020-10-12 21:38 UTC, Davidantu commented on src/Components/SettingsScreen.jsx
> +      validateBaby(BabyDOB) === false
Just noticed that I forgot to fix the function call in that line. Will fix that, thank you.

2020-10-12 21:39 UTC, Davidantu commented on src/Components/SettingsScreen.jsx
> +      validateDOB(Dob) === false ||
Not sure what you mean by this, should I assign a variable instead of calling the validate functions so many times?

2020-10-12 21:49 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +      validateDOB(Dob) === false ||
nono that the variables should follow camelCase.
So rename the variables please :)

2020-10-12 21:59 UTC, Davidantu commented on src/Components/SettingsScreen.jsx
> +      validateDOB(Dob) === false ||
So something like this right?
    validateDOB(**dob**) === false

Then I would change my functions to look like:
    function validateDOB(**dob**)...

2020-10-12 22:37 UTC, edumorlom commented on src/Components/SettingsScreen.jsx
> +      validateDOB(Dob) === false ||
yeah, validateDob() too instead of validateDOB.
Basically all variables should follow camelCase except classes.

const thisIsMyFunction = thisIsMyParameter  => return true;

const thisIsMyObject = new ThisIsMyClass()

2020-10-14 03:06 UTC, edumorlom commented
Looks good, thanks!

2020-10-14 03:07 UTC, merged