Create facilities
edumorlom/moms-infants-healthy pull request #196
Opened 2020-10-26 20:43 UTC by jgonz11

2020-10-27 14:36 UTC, edumorlom commented
please fix conflicts

2020-10-27 16:57 UTC, edumorlom requested changes

2020-10-27 16:57 UTC, edumorlom commented on src/Components/Homepage.jsx
> +>>>>>>> acb8192fc8d6d2edaefad2e5a63894c8e7f3a971
They were fixed correctly :(

2020-10-27 17:59 UTC, jgonz11 reviewed
All files have been reviewed and fixed all conflicts

2020-10-27 17:59 UTC, jgonz11 commented on src/en_US.json
> +  "facilities": "Facilities"
facilities

2020-10-29 17:28 UTC, edumorlom approved these changes

2020-10-29 17:28 UTC, edumorlom commented
Seems to work! Thanks!

2020-10-29 17:28 UTC, merged