Fixes Issue #325
edumorlom/moms-infants-healthy pull request #343
Opened 2021-09-21 19:02 UTC by lroche823

Makes the buttons in the WIC feeding section unclickable. They still vibrate when pressed on but don't do anything or cause any crashes from my tests. LMK if I should figure out how to stop the vibration as well

2021-09-21 20:02 UTC, edumorlom commented
what happens if you remove the onPress? onPress should only be added if there is an onpress event, but in this case there should not be an unpress event. Why do we have onPress?

2021-09-21 20:02 UTC, edumorlom commented
@lroche823

2021-09-21 20:15 UTC, lroche823 commented
> 
> 
> what happens if you remove the onPress? onPress should only be added if there is an onpress event, but in this case there should not be an unpress event. Why do we have onPress?

I did try removing onPress altogether but it gave me an error saying something like "onPress must be a valid function", as if it was required for the button to work.

2021-09-21 20:27 UTC, edumorlom commented
The way to fix this issue is to check if props.onPress exists prior to doing props.onPress(). @lroche823 

Modify the following file: https://github.com/edumorlom/moms-infants-healthy/blob/development/src/Components/SelectionButton.jsx


Once you have done that, you will be able to remove the onPress prop/parameter.

```
  const onPress = () => {
    if (props.onPress) {
    Haptics.selectionAsync().then();
    props.onPress();}
}
```

2021-09-25 16:47 UTC, julianlopez6850 commented
Hey, I tested this and you did get rid of the error messages on click, but like you said, there are still vibrations/highlighting when you click on a button. I think to fix this, you can replace every instance of SelectionButton  with BetterMenu and keep the inner contents of the views the same. 

(  BetterMenu is used lower on the same js script under the if(age == -1) and if(age == -2).  )

This should fix the problem, since the BetterMenu textboxes are not clickable

2021-09-27 13:41 UTC, julianlopez6850 commented
Update Review: I hadn't done git pull origin in the branch before I started testing, so I was testing an older version of the branch. So now I just tested the updated pull request.

I no longer get the vibrations upon clicking the textboxes, but I still get the problem where the textboxes get highlighted if you click and hold them for anywhere over like .1s

I still think that the fix I mentioned in the above review will fix this highlighting issue.

2021-09-27 15:19 UTC, julianlopez6850 requested changes, later dismissed
Hey @lroche823 . I created a new pull request #350 to merge into your branch with the fixes I mentioned (along with a couple stylistic changes in other parts of the same page). 

If you can check it out and test it, and it works, you can merge it into your own branch and then get one more person to review afterwards and it should be ready to merge to development.

2021-09-28 13:43 UTC, OscarHSanchez108 approved these changes
Tested the update and found that none of the items in reference were clickable, or got highlighted.

2021-09-29 13:05 UTC, julianlopez6850 approved these changes

2021-09-30 13:29 UTC, julianlopez6850 commented
Merging, per approval of Eduardo

2021-09-30 13:29 UTC, merged