add website button to std info
edumorlom/moms-infants-healthy pull request #560
Opened 2022-11-03 18:57 UTC by lroche823

resolves suggestion #446
i added the website button to the top of the list because i felt like that looks better, if reviewers think it would be nicer at the bottom i can easily move it.

2022-11-11 02:09 UTC, VenegasJustin approved these changes
Looks good, makes sense for the websites to the first resource to be seen

2022-11-11 23:15 UTC, Elijahx requested changes
Buttons were populated. However, redirection failed for all links. I noticed a missing l at the end of html in the links. In addition, I tested that the links work with http:// as the beginning format like so 'http://www.cdc.gov/zika/index.html'.

2022-11-14 21:10 UTC, Elijahx approved these changes
These fixes worked great on my device. Buttons were populated and link redirection was a success.

2022-11-14 23:03 UTC, VenegasJustin approved these changes

2022-11-14 23:03 UTC, VenegasJustin approved these changes

2022-11-14 23:04 UTC, VenegasJustin approved these changes

2022-11-14 23:10 UTC, VenegasJustin approved these changes

2022-11-14 23:10 UTC, VenegasJustin approved these changes

2022-11-14 23:11 UTC, VenegasJustin approved these changes

2022-11-14 23:17 UTC, VenegasJustin approved these changes

2022-11-14 23:18 UTC, VenegasJustin approved these changes

2022-11-17 17:35 UTC, merged