Moved Continue button up on all steps of sign up
edumorlom/moms-infants-healthy pull request #637
Opened 2023-06-21 23:07 UTC by daviddelgadol

Now the user does not have to tap anywhere to remove the keyboard and is able to continue the signing-up process. The continue button will be always in sight regardless of if the keyboard is present.

2023-06-23 17:49 UTC, probycode approved these changes
looks good

2023-06-25 05:31 UTC, RoniRaad requested changes
This completely breaks the flow registration. The changes are also not consistent with the issue they're meant to solve.

2023-06-25 14:05 UTC, JosephBargallo requested changes
Flow of sign up was out of order and button failed to move when testing the code.

2023-06-25 17:36 UTC, Sunnex requested changes
Ran it and for some reason it did not work for me, the continue button stayed at the bottom. Not only that the flow of the sign up page was out of order for me too. For instance, instead of asking me for my name and date of birth first, it skipped straight to creating the password page.

2023-06-25 19:05 UTC, daviddelgadol commented
PR Closed due to issues. New PR will be created.

2023-06-25 19:30 UTC, JosephBargallo requested changes
Sign up order is now fixed, but the button is not moving to desired spot on IOS.

2023-06-25 19:39 UTC, closed without merging