Update app.json
edumorlom/moms-infants-healthy pull request #639
Opened 2023-06-23 19:08 UTC by probycode

2023-06-25 05:24 UTC, RoniRaad approved these changes

2023-06-25 05:39 UTC, RoniRaad commented
Look good.

2023-06-25 15:05 UTC, JosephBargallo requested changes
I still seem to be getting the error on my end.[
![Issue #639](https://github.com/edumorlom/nuMom/assets/101291408/92cea54f-0ef8-498f-b027-6def94058070)
](url)

2023-07-07 15:26 UTC, JosephBargallo approved these changes
Error is not longer appearing when launching the app.
![image](https://github.com/edumorlom/nuMom/assets/101291408/bdadb5d0-497b-4cdf-8837-8bcccd3697ff)

2023-07-07 15:27 UTC, merged